# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tftag < Formula
  desc "DRY approach to tagging Terraform resources"
  homepage "https://github.com/bschaatsbergen/tftag"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bschaatsbergen/tftag/releases/download/v0.1.0/tftag_0.1.0_darwin_amd64.tar.gz"
      sha256 "c1bf425061b5e80a4ca314caa3ced564f581266d15925b9b9b1633c6dc8a9043"

      def install
        bin.install "tftag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bschaatsbergen/tftag/releases/download/v0.1.0/tftag_0.1.0_darwin_arm64.tar.gz"
      sha256 "7cb0c0330d1c1058c19fa4ac2b16fe42777637bc84f520adee6320c7d1c5d834"

      def install
        bin.install "tftag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bschaatsbergen/tftag/releases/download/v0.1.0/tftag_0.1.0_linux_amd64.tar.gz"
      sha256 "4b2985cc931a8a25d7edacc1eef03f8be97dc36b82763475992c84fcd804ab64"

      def install
        bin.install "tftag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bschaatsbergen/tftag/releases/download/v0.1.0/tftag_0.1.0_linux_arm64.tar.gz"
      sha256 "dd3d4d1fc36c42788fb531b614667255526a8159e4ec2d290b4de12bc00eb6a2"

      def install
        bin.install "tftag"
      end
    end
  end

  test do
    system "#{bin}/tftag -v"
  end
end
